region = "us-central1"
region_zone = "us-central1-a"
project = "gluster-k8s-18217"
image = "ubuntu-os-cloud/ubuntu-1404-trusty-v20161020"
credentials_file_path = "credentials/terraform.json"
public_key_path = "credentials/harshals_pub.txt"
private_key_path = "credentials/harshals.ppk"
machine_type = "n1-standard-2"